cryptography/urls.py
from django.urls import path
from . import views

app_name= 'cryptography'

urlpatterns = [
    path('', views.encrypt_decrypt, name='encrypt_decrypt'),
]

cyberToolBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('password-strength/', include('password_strength.urls')),
    path('keylogger/', include('keylogger.urls')),
    path('cryptography/', include('cryptography.urls')),
    path('password-cracker/', include('password_cracker.urls')),
    path('phishing-detector/', include('phishing_detector.urls')),
    path('geolocation-finder/', include('geolocation_finder.urls')),
    path('dns-lookup/', include('dns_lookup.urls')),
    path('ssl-checker/', include('ssl_checker.urls')),
    path('osint-aggregator/', include('osint_aggregator.urls')),
    path('port-scanner/', include('port_scanner.urls')),
    path('api-security-tester/', include('api_security_tester.urls')),
    path('social-engineering/', include('social_engineering.urls')),
    path('subnet-calculator/', include('subnet_calculator.urls')),
    path('password-generator/', include('password_generator.urls')),
    path('network-speed/', include('network_speed.urls')),
]

dns_lookup/urls.py
from django.urls import path
from . import views

app_name = 'dns_lookup'

urlpatterns = [
    path('', views.dns_lookup, name='dns_lookup'),
]

keylogger/urls.py
from django.urls import path
from . import views

app_name = 'keylogger'

urlpatterns = [
    path('', views.logger, name='logger'),
    path('log/', views.log_keys, name='log_keys'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

ssl_checker/urls.py
from django.urls import path
from . import views

app_name = 'ssl_checker'

urlpatterns = [
    path('', views.ssl_tls_checker, name='ssl_tls_checker'),
]

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'main/templates/home.html')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Cyber Assist</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary py-3">
  <div class="container-fluid">
    <a href="{% url 'home' %}">
                    <img src="{% static 'images/logo.png' %}" alt="Cybersecurity Toolkit Logo" width="250px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-5">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Security & Monitoring Tools
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'keylogger:logger' %}">Keylogger</a></li>
            <li><a class="dropdown-item" href="{% url 'password_strength:checker' %}">Password Strength Checker</a></li>
              <li><a class="dropdown-item" href="{% url 'phishing_detector:phishing_detector' %}">Phishing URL Detector</a></li>
              <li><a class="dropdown-item" href="{% url 'osint_aggregator:osint_aggregator' %}">OSINT Aggregator</a></li>
              <li><a class="dropdown-item" href="{% url 'api_security_tester:api_security_tester' %}">API Security Tester</a></li>
              <li><a class="dropdown-item" href="{% url 'social_engineering:social_engineering_simulator' %}">Social Engineering Simulator</a></li>
              <li><a class="dropdown-item" href="{% url 'password_generator:password_generator' %}">Secure Password Generator</a></li>
          </ul>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cryptography & Hashing Tools
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'cryptography:encrypt_decrypt' %}">Cryptography Tool</a></li>
              <li><a class="dropdown-item" href="{% url 'password_cracker:cracker' %}">Hash Generator</a></li>
          </ul>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Network & DNS Tools
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'geolocation_finder:geolocation_finder' %}">IP Geolocation Finder</a></li>
            <li><a class="dropdown-item" href="{% url 'dns_lookup:dns_lookup' %}">DNS Lookup Tool</a></li>
            <li><a class="dropdown-item" href="{% url 'ssl_checker:ssl_tls_checker' %}">SSL/TLS Certificate Checker</a></li>
              <li><a class="dropdown-item" href="{% url 'port_scanner:port_scanner' %}">Port Scanner</a></li>
              <li><a class="dropdown-item" href="{% url 'subnet_calculator:subnet_calculator' %}">Subnet Calculator</a></li>
            <li><a class="dropdown-item" href="{% url 'network_speed:network_speed' %}">Network Speed Tester</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

main/templates/home.html
{% extends 'main/templates/base.html' %}

{% block title %} Home {% endblock %}

{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-lock" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> Password Strength Checker</h5>
                    <hr />
                    <p class="card-text">Assess the robustness of your passwords to ensure they are strong and secure against potential threats.</p>
                    <a href="{% url 'password_strength:checker' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-keyboard" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> Keylogger</h5>
                    <hr />
                    <p class="card-text">Monitor and record keyboard inputs to detect unauthorized activity.</p>
                    <a href="{% url 'keylogger:logger' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-lock" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> Cryptography Tool</h5>
                    <hr />
                    <p class="card-text">Encrypt and decrypt messages to secure sensitive information.</p>
                    <a href="{% url 'cryptography:encrypt_decrypt' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-hashtag" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> Hash Generator</h5>
                    <hr />
                    <p class="card-text">Attempt to generate all the possible hash values from the given plain text.</p>
                    <a href="{% url 'password_cracker:cracker' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-exclamation-triangle" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> Phishing URL Detector</h5>
                    <hr />
                    <p class="card-text">A tool that checks URLs for phishing indicators to determine their safety.</p>
                    <a href="{% url 'phishing_detector:phishing_detector' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-map-marker-alt" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> IP Geolocation Finder</h5>
                    <hr />
                    <p class="card-text">A tool that locates the geographical position of an IP address.</p>
                    <a href="{% url 'geolocation_finder:geolocation_finder' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-database" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> DNS Lookup Tool</h5>
                    <hr />
                    <p class="card-text">Quickly retrieves detailed DNS records for a specified domain name.</p>
                    <a href="{% url 'dns_lookup:dns_lookup' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-shield-alt" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i> SSL/TLS Certificate Checker</h5>
                    <hr />
                    <p class="card-text">Check the validity and security of an SSL/TLS certificate for any domain.</p>
                    <a href="{% url 'ssl_checker:ssl_tls_checker' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-search" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        OSINT Aggregator</h5>
                    <hr />
                    <p class="card-text">Collect and analyze publicly available information about domains and email addresses for enhanced threat intelligence.</p>
                    <a href="{% url 'osint_aggregator:osint_aggregator' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-network-wired" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        Port Scanner</h5>
                    <hr />
                    <p class="card-text">Identify open ports and services on a target system to assess network security and uncover vulnerabilities.</p>
                    <a href="{% url 'port_scanner:port_scanner' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                <h5 class="card-title"><i class="fas fa-shield-alt" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        API Security Tester</h5>
                    <hr />
                    <p class="card-text">Analyze and identify vulnerabilities in your APIs to ensure they are secure against potential threats.</p>
                    <a href="{% url 'api_security_tester:api_security_tester' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                <h5 class="card-title"><i class="fas fa-mask" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        Social Engineering Simulator</h5>
                    <hr />
                    <p class="card-text">Simulates social engineering attacks to test and improve organizational resilience against manipulative tactics and phishing.</p>
                    <a href="{% url 'social_engineering:social_engineering_simulator' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-network-wired" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        Subnet Calculator</h5>
                    <hr />
                    <p class="card-text">Calculate IP subnets, network addresses, and broadcast addresses for efficient network management.</p>
                    <a href="{% url 'subnet_calculator:subnet_calculator' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-key" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        Secure Password Generator</h5>
                    <hr />
                    <p class="card-text">Generate strong, random passwords to enhance your security.</p>
                    <a href="{% url 'password_generator:password_generator' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                <h5 class="card-title"><i class="fas fa-tachometer-alt" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        Network Speed Tester</h5>
                    <hr />
                    <p class="card-text">Measure the upload and download speed of your network connection.</p>
                    <a href="{% url 'network_speed:network_speed' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card tool-item" style="width: 100%;">
                <div class="card-body">
                <h5 class="card-title"><i class="fas fa-mask" style="font-size: 1.5rem; color: #007bff; margin-right: 0.5rem;"></i>
                        Social Engineering Simulator</h5>
                    <hr />
                    <p class="card-text">Simulates social engineering attacks to test and improve organizational resilience against manipulative tactics and phishing.</p>
                    <a href="{% url 'social_engineering:social_engineering_simulator' %}" class="btn btn-primary"><i class="fas fa-arrow-right"></i> Go to Tool</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}